# Project 3: Smart Beta Portfolio and Portfolio Optimization

## Overview


Smart beta has a broad meaning, but we can say in practice that when we use the universe of stocks from an index, and then apply some weighting scheme other than market cap weighting, it can be considered a type of smart beta fund.  A Smart Beta portfolio generally gives investors exposure or "beta" to one or more types of market characteristics (or factors) that are believed to predict prices while giving investors a diversified broad exposure to a particular market. Smart Beta portfolios generally target momentum, earnings quality, low volatility, and dividends or some combination. Smart Beta Portfolios are generally rebalanced infrequently and follow relatively simple rules or algorithms that are passively managed.  Model changes to these types of funds are also rare requiring prospectus filings with US Security and Exchange Commission in the case of US focused mutual funds or ETFs.. Smart Beta portfolios are generally long-only, they do not short stocks.

In contrast, a purely alpha-focused quantitative fund may use multiple models or algorithms to create a portfolio. The portfolio manager retains discretion in upgrading or changing the types of models and how often to rebalance the portfolio in attempt to maximize performance in comparison to a stock benchmark.  Managers may have discretion to short stocks in portfolios.

Imagine you're a portfolio manager, and wish to try out some different portfolio weighting methods.

One way to design portfolio is to look at certain accounting measures (fundamentals) that, based on past trends, indicate stocks that produce better results.  


For instance, you may start with a hypothesis that dividend-issuing stocks tend to perform better than stocks that do not. This may not always be true of all companies; for instance, Apple does not issue dividends, but has had good historical performance.  The hypothesis about dividend-paying stocks may go something like this: 

Companies that regularly issue dividends may also be more prudent in allocating their available cash, and may indicate that they are more conscious of prioritizing shareholder interests.  For example, a CEO may decide to reinvest cash into pet projects that produce low returns.  Or, the CEO may do some analysis, identify that reinvesting within the company produces lower returns compared to a diversified portfolio, and so decide that shareholders would be better served if they were given the cash (in the form of dividends).  So according to this hypothesis, dividends may be both a proxy for how the company is doing (in terms of earnings and cash flow), but also a signal that the company acts in the best interest of its shareholders.  Of course, it's important to test whether this works in practice.


You may also have another hypothesis, with which you wish to design a portfolio that can then be made into an ETF.  You may find that investors may wish to invest in passive beta funds, but wish to have less risk exposure (less volatility) in their investments.  The goal of having a low volatility fund that still produces returns similar to an index may be appealing to investors who have a shorter investment time horizon, and so are more risk averse.

So the objective of your proposed portfolio is to design a portfolio that closely tracks an index, while also minimizing the portfolio variance.  Also, if this portfolio can match the returns of the index with less volatility, then it has a higher risk-adjusted return (same return, lower volatility).

Smart Beta ETFs can be designed with both of these two general methods (among others): alternative weighting and minimum volatility ETF.


## Instructions
Each problem consists of a function to implement and instructions on how to implement the function.  The parts of the function that need to be implemented are marked with a `# TODO` comment. After implementing the function, run the cell to test it against the unit tests we've provided. For each problem, we provide one or more unit tests from our `project_tests` package. These unit tests won't tell you if your answer is correct, but will warn you of any major errors. Your code will be checked for the correct solution when you submit it to Udacity.

## Packages
When you implement the functions, you'll only need to you use the packages you've used in the classroom, like [Pandas](https://pandas.pydata.org/) and [Numpy](http://www.numpy.org/). These packages will be imported for you. We recommend you don't add any import statements, otherwise the grader might not be able to run your code.

The other packages that we're importing are `helper`, `project_helper`, and `project_tests`. These are custom packages built to help you solve the problems.  The `helper` and `project_helper` module contains utility functions and graph functions. The `project_tests` contains the unit tests for all the problems.
### Install Packages

In [1]:
import sys
!{sys.executable} -m pip install -r requirements.txt

    100% |████████████████████████████████| 880kB 7.8MB/s eta 0:00:01    82% |██████████████████████████▍     | 727kB 12.0MB/s eta 0:00:01
    100% |████████████████████████████████| 12.2MB 3.4MB/s eta 0:00:01   23% |███████▍                        | 2.8MB 24.8MB/s eta 0:00:01    34% |███████████                     | 4.2MB 31.6MB/s eta 0:00:01    47% |███████████████▏                | 5.8MB 28.9MB/s eta 0:00:01    83% |██████████████████████████▊     | 10.1MB 34.2MB/s eta 0:00:01
    100% |████████████████████████████████| 26.2MB 1.1MB/s eta 0:00:01  1% |▌                               | 430kB 28.0MB/s eta 0:00:01    24% |████████                        | 6.5MB 32.4MB/s eta 0:00:01    42% |█████████████▌                  | 11.1MB 32.1MB/s eta 0:00:01    99% |████████████████████████████████| 26.2MB 28.5MB/s eta 0:00:01
    100% |████████████████████████████████| 1.1MB 16.4MB/s ta 0:00:01    50% |████████████████                | 542kB 25.4MB/s eta 0:00:01
    100% |███████████████████

    100% |████████████████████████████████| 153kB 11.9MB/s ta 0:00:01
  Running setup.py bdist_wheel for cvxpy ... done
  Stored in directory: /root/.cache/pip/wheels/2b/60/0b/0c2596528665e21d698d6f84a3406c52044c7b4ca6ac737cf3
  Running setup.py bdist_wheel for plotly ... done
  Stored in directory: /root/.cache/pip/wheels/98/54/81/dd92d5b0858fac680cd7bdb8800eb26c001dd9f5dc8b1bc0ba
  Running setup.py bdist_wheel for scs ... done
  Stored in directory: /root/.cache/pip/wheels/df/d0/79/37ea880586da03c620ca9ecd5e42adbd86bc6ea84363965c5f
  Running setup.py bdist_wheel for multiprocess ... done
  Stored in directory: /root/.cache/pip/wheels/96/20/ac/9f1d164f7d81787cd6f4401b1d05212807d021fbbbcc301b82
  Running setup.py bdist_wheel for dill ... done
  Stored in directory: /root/.cache/pip/wheels/59/b1/91/f02e76c732915c4015ab4010f3015469866c1eb9b14058d8e7
Successfully built cvxpy plotly scs multiprocess dill
tensorflow 1.3.0 requires tensorflow-tensorboard<0.2.0,>=0.1.0, which is not installed

### Load Packages

In [2]:
import pandas as pd
import numpy as np
import helper
import project_helper
import project_tests

## Market Data
### Load Data
For this universe of stocks, we'll be selecting large dollar volume stocks. We're using this universe, since it is highly liquid.

In [3]:
df = pd.read_csv('../../data/project_3/eod-quotemedia.csv')

percent_top_dollar = 0.2
high_volume_symbols = project_helper.large_dollar_volume_stocks(df, 'adj_close', 'adj_volume', percent_top_dollar)
df = df[df['ticker'].isin(high_volume_symbols)]

close = df.reset_index().pivot(index='date', columns='ticker', values='adj_close')
volume = df.reset_index().pivot(index='date', columns='ticker', values='adj_volume')
dividends = df.reset_index().pivot(index='date', columns='ticker', values='dividends')

### View Data
To see what one of these 2-d matrices looks like, let's take a look at the closing prices matrix.

In [4]:
project_helper.print_dataframe(close)

# Part 1: Smart Beta Portfolio
In Part 1 of this project, you'll build a portfolio using dividend yield to choose the portfolio weights. A portfolio such as this could be incorporated into a smart beta ETF.  You'll compare this portfolio to a market cap weighted index to see how well it performs. 

Note that in practice, you'll probably get the index weights from a data vendor (such as companies that create indices, like MSCI, FTSE, Standard and Poor's), but for this exercise we will simulate a market cap weighted index.

## Index Weights
The index we'll be using is based on large dollar volume stocks. Implement `generate_dollar_volume_weights` to generate the weights for this index. For each date, generate the weights based on dollar volume traded for that date. For example, assume the following is close prices and volume data:
```
                 Prices
               A         B         ...
2013-07-08     2         2         ...
2013-07-09     5         6         ...
2013-07-10     1         2         ...
2013-07-11     6         5         ...
...            ...       ...       ...

                 Volume
               A         B         ...
2013-07-08     100       340       ...
2013-07-09     240       220       ...
2013-07-10     120       500       ...
2013-07-11     10        100       ...
...            ...       ...       ...
```
The weights created from the function `generate_dollar_volume_weights` should be the following:
```
               A         B         ...
2013-07-08     0.126..   0.194..   ...
2013-07-09     0.759..   0.377..   ...
2013-07-10     0.075..   0.285..   ...
2013-07-11     0.037..   0.142..   ...
...            ...       ...       ...
```

In [5]:
def generate_dollar_volume_weights(close, volume):
    """
    Generate dollar volume weights.

    Parameters
    ----------
    close : DataFrame
        Close price for each ticker and date
    volume : str
        Volume for each ticker and date

    Returns
    -------
    dollar_volume_weights : DataFrame
        The dollar volume weights for each ticker and date
    """
    assert close.index.equals(volume.index)
    assert close.columns.equals(volume.columns)
    
    #TODO: Implement function
    dollar_volume_weights = (close * volume)
    volsum = np.sum(dollar_volume_weights, axis=1)

    dollar_volume_weights = dollar_volume_weights.divide(volsum, axis=0)
 
    return dollar_volume_weights

project_tests.test_generate_dollar_volume_weights(generate_dollar_volume_weights)

Tests Passed


### View Data
Let's generate the index weights using `generate_dollar_volume_weights` and view them using a heatmap.

In [6]:
index_weights = generate_dollar_volume_weights(close, volume)
project_helper.plot_weights(index_weights, 'Index Weights')

## Portfolio Weights
Now that we have the index weights, let's choose the portfolio weights based on dividend. You would normally calculate the weights based on trailing dividend yield, but we'll simplify this by just calculating the total dividend yield over time.

Implement `calculate_dividend_weights` to return the weights for each stock based on its total dividend yield over time. This is similar to generating the weight for the index, but it's using dividend data instead.
For example, assume the following is `dividends` data:
```
                 Prices
               A         B
2013-07-08     0         0
2013-07-09     0         1
2013-07-10     0.5       0
2013-07-11     0         0
2013-07-12     2         0
...            ...       ...
```
The weights created from the function `calculate_dividend_weights` should be the following:
```
               A         B
2013-07-08     NaN       NaN
2013-07-09     0         1
2013-07-10     0.333..   0.666..
2013-07-11     0.333..   0.666..
2013-07-12     0.714..   0.285..
...            ...       ...
```

In [7]:
def calculate_dividend_weights(dividends):
    """
    Calculate dividend weights.

    Parameters
    ----------
    dividends : DataFrame
        Dividend for each stock and date

    Returns
    -------
    dividend_weights : DataFrame
        Weights for each stock and date
    """
    #TODO: Implement function
    dividend_weights = dividends.cumsum().divide(np.sum(dividends.cumsum(), axis=1), axis=0)

    return dividend_weights

project_tests.test_calculate_dividend_weights(calculate_dividend_weights)

Tests Passed


### View Data
Just like the index weights, let's generate the ETF weights and view them using a heatmap.

In [8]:
etf_weights = calculate_dividend_weights(dividends)
project_helper.plot_weights(etf_weights, 'ETF Weights')

## Returns
Implement `generate_returns` to generate returns data for all the stocks and dates from price data. You might notice we're implementing returns and not log returns. Since we're not dealing with volatility, we don't have to use log returns.

In [9]:
def generate_returns(prices):
    """
    Generate returns for ticker and date.

    Parameters
    ----------
    prices : DataFrame
        Price for each ticker and date

    Returns
    -------
    returns : Dataframe
        The returns for each ticker and date
    """
    #TODO: Implement function
    returns = (prices - prices.shift(1)) / prices.shift(1)

    return returns

project_tests.test_generate_returns(generate_returns)

Tests Passed


### View Data
Let's generate the closing returns using `generate_returns` and view them using a heatmap.

In [10]:
returns = generate_returns(close)
project_helper.plot_returns(returns, 'Close Returns')

## Weighted Returns
With the returns of each stock computed, we can use it to compute the returns for an index or ETF. Implement `generate_weighted_returns` to create weighted returns using the returns and weights.

In [11]:
def generate_weighted_returns(returns, weights):
    """
    Generate weighted returns.

    Parameters
    ----------
    returns : DataFrame
        Returns for each ticker and date
    weights : DataFrame
        Weights for each ticker and date

    Returns
    -------
    weighted_returns : DataFrame
        Weighted returns for each ticker and date
    """
    assert returns.index.equals(weights.index)
    assert returns.columns.equals(weights.columns)
    
    #TODO: Implement function
    weighted_returns = returns * weights

    return weighted_returns

project_tests.test_generate_weighted_returns(generate_weighted_returns)

Tests Passed


### View Data
Let's generate the ETF and index returns using `generate_weighted_returns` and view them using a heatmap.

In [12]:
index_weighted_returns = generate_weighted_returns(returns, index_weights)
etf_weighted_returns = generate_weighted_returns(returns, etf_weights)
project_helper.plot_returns(index_weighted_returns, 'Index Returns')
project_helper.plot_returns(etf_weighted_returns, 'ETF Returns')

## Cumulative Returns
To compare performance between the ETF and Index, we're going to calculate the tracking error. Before we do that, we first need to calculate the index and ETF comulative returns. Implement `calculate_cumulative_returns` to calculate the cumulative returns over time given the returns.

In [13]:
def calculate_cumulative_returns(returns):
    """
    Calculate cumulative returns.

    Parameters
    ----------
    returns : DataFrame
        Returns for each ticker and date

    Returns
    -------
    cumulative_returns : Pandas Series
        Cumulative returns for each date
    """
    #TODO: Implement function
    cumulative_returns = np.cumprod(np.sum(returns, axis=1)+1, axis=0)
    
    return cumulative_returns

project_tests.test_calculate_cumulative_returns(calculate_cumulative_returns)

Tests Passed


### View Data
Let's generate the ETF and index cumulative returns using `calculate_cumulative_returns` and compare the two.

In [14]:
index_weighted_cumulative_returns = calculate_cumulative_returns(index_weighted_returns)
etf_weighted_cumulative_returns = calculate_cumulative_returns(etf_weighted_returns)
project_helper.plot_benchmark_returns(index_weighted_cumulative_returns, etf_weighted_cumulative_returns, 'Smart Beta ETF vs Index')

## Tracking Error
In order to check the performance of the smart beta portfolio, we can calculate the annualized tracking error against the index. Implement `tracking_error` to return the tracking error between the ETF and benchmark.

For reference, we'll be using the following annualized tracking error function:
$$ TE = \sqrt{252} * SampleStdev(r_p - r_b) $$

Where $ r_p $ is the portfolio/ETF returns and $ r_b $ is the benchmark returns.

_Note: When calculating the sample standard deviation, the delta degrees of freedom is 1, which is the also the default value._

In [15]:
def tracking_error(benchmark_returns_by_date, etf_returns_by_date):
    """
    Calculate the tracking error.

    Parameters
    ----------
    benchmark_returns_by_date : Pandas Series
        The benchmark returns for each date
    etf_returns_by_date : Pandas Series
        The ETF returns for each date

    Returns
    -------
    tracking_error : float
        The tracking error
    """
    assert benchmark_returns_by_date.index.equals(etf_returns_by_date.index)
    
    #TODO: Implement function
    tracking_error = np.sqrt(252) * np.std(etf_returns_by_date-benchmark_returns_by_date, ddof=1)

    return tracking_error

project_tests.test_tracking_error(tracking_error)

Tests Passed


### View Data
Let's generate the tracking error using `tracking_error`.

In [16]:
smart_beta_tracking_error = tracking_error(np.sum(index_weighted_returns, 1), np.sum(etf_weighted_returns, 1))
print('Smart Beta Tracking Error: {}'.format(smart_beta_tracking_error))

Smart Beta Tracking Error: 0.1020761483200753


# Part 2: Portfolio Optimization

Now, let's create a second portfolio.  We'll still reuse the market cap weighted index, but this will be independent of the dividend-weighted portfolio that we created in part 1.

We want to both minimize the portfolio variance and also want to closely track a market cap weighted index.  In other words, we're trying to minimize the distance between the weights of our portfolio and the weights of the index.

$Minimize \left [ \sigma^2_p + \lambda \sqrt{\sum_{1}^{m}(weight_i - indexWeight_i)^2} \right  ]$ where $m$ is the number of stocks in the portfolio, and $\lambda$ is a scaling factor that you can choose.

Why are we doing this? One way that investors evaluate a fund is by how well it tracks its index. The fund is still expected to deviate from the index within a certain range in order to improve fund performance.  A way for a fund to track the performance of its benchmark is by keeping its asset weights similar to the weights of the index.  We’d expect that if the fund has the same stocks as the benchmark, and also the same weights for each stock as the benchmark, the fund would yield about the same returns as the benchmark. By minimizing a linear combination of both the portfolio risk and distance between portfolio and benchmark weights, we attempt to balance the desire to minimize portfolio variance with the goal of tracking the index.


## Covariance
Implement `get_covariance_returns` to calculate the covariance of the `returns`. We'll use this to calculate the portfolio variance.

If we have $m$ stock series, the covariance matrix is an $m \times m$ matrix containing the covariance between each pair of stocks.  We can use [`Numpy.cov`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cov.html) to get the covariance.  We give it a 2D array in which each row is a stock series, and each column is an observation at the same period of time. For any `NaN` values, you can replace them with zeros using the [`DataFrame.fillna`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.fillna.html) function.

The covariance matrix $\mathbf{P} = 
\begin{bmatrix}
\sigma^2_{1,1} & ... & \sigma^2_{1,m} \\ 
... & ... & ...\\
\sigma_{m,1} & ... & \sigma^2_{m,m}  \\
\end{bmatrix}$

In [21]:
def get_covariance_returns(returns):
    """
    Calculate covariance matrices.

    Parameters
    ----------
    returns : DataFrame
        Returns for each ticker and date

    Returns
    -------
    returns_covariance  : 2 dimensional Ndarray
        The covariance of the returns
    """
    #TODO: Implement function
    returns = returns.fillna(0).T
    returns_covariance = np.cov(returns)

    return returns_covariance

project_tests.test_get_covariance_returns(get_covariance_returns)

[[0.89856076 0.7205586  0.8458721 ]
 [0.7205586  0.78707297 0.76450378]
 [0.8458721  0.76450378 0.83182775]]
Tests Passed


### View Data
Let's look at the covariance generated from `get_covariance_returns`.

In [22]:
covariance_returns = get_covariance_returns(returns)
covariance_returns = pd.DataFrame(covariance_returns, returns.columns, returns.columns)

covariance_returns_correlation = np.linalg.inv(np.diag(np.sqrt(np.diag(covariance_returns))))
covariance_returns_correlation = pd.DataFrame(
    covariance_returns_correlation.dot(covariance_returns).dot(covariance_returns_correlation),
    covariance_returns.index,
    covariance_returns.columns)

project_helper.plot_covariance_returns_correlation(
    covariance_returns_correlation,
    'Covariance Returns Correlation Matrix')

[[5.31791451e-04 7.21251856e-05 9.55847963e-05 ... 4.55526842e-05
  1.26756746e-04 4.27885833e-05]
 [7.21251856e-05 2.14185487e-04 4.87000321e-05 ... 3.43023358e-05
  8.17766960e-05 4.13786801e-05]
 [9.55847963e-05 4.87000321e-05 2.64537496e-04 ... 3.32734532e-05
  1.11616723e-04 5.40669112e-05]
 ...
 [4.55526842e-05 3.43023358e-05 3.32734532e-05 ... 1.14424083e-04
  3.48568802e-05 2.79122492e-05]
 [1.26756746e-04 8.17766960e-05 1.11616723e-04 ... 3.48568802e-05
  7.17162013e-04 8.42633668e-05]
 [4.27885833e-05 4.13786801e-05 5.40669112e-05 ... 2.79122492e-05
  8.42633668e-05 1.29561995e-04]]


In [ ]:
# portfolio variance
We can write the portfolio variance $\sigma^2_p = \mathbf{x^T} \mathbf{P} \mathbf{x}$

Recall that the $\mathbf{x^T} \mathbf{P} \mathbf{x}$ is called the quadratic form.
We can use the cvxpy function `quad_form(x,P)` to get the quadratic form.

### Distance from index weights
We want portfolio weights that track the index closely.  So we want to minimize the distance between them.
Recall from the Pythagorean theorem that you can get the distance between two points in an x,y plane by adding the square of the x and y distances and taking the square root.  Extending this to any number of dimensions is called the L2 norm.  So: $\sqrt{\sum_{1}^{n}(weight_i - indexWeight_i)^2}$  Can also be written as $\left \| \mathbf{x} - \mathbf{index} \right \|_2$.  There's a cvxpy function called [norm()](https://www.cvxpy.org/api_reference/cvxpy.atoms.other_atoms.html#norm)
`norm(x, p=2, axis=None)`.  The default is already set to find an L2 norm, so you would pass in one argument, which is the difference between your portfolio weights and the index weights.

### objective function
We want to minimize both the portfolio variance and the distance of the portfolio weights from the index weights.
We also want to choose a `scale` constant, which is $\lambda$ in the expression. 

$\mathbf{x^T} \mathbf{P} \mathbf{x} + \lambda \left \| \mathbf{x} - \mathbf{index} \right \|_2$


This lets us choose how much priority we give to minimizing the difference from the index, relative to minimizing the variance of the portfolio.  If you choose a higher value for `scale` ($\lambda$).

We can find the objective function using cvxpy `objective = cvx.Minimize()`.  Can you guess what to pass into this function?



### constraints
We can also define our constraints in a list.  For example, you'd want the weights to sum to one. So $\sum_{1}^{n}x = 1$.  You may also need to go long only, which means no shorting, so no negative weights.  So $x_i >0 $ for all $i$. you could save a variable as `[x >= 0, sum(x) == 1]`, where x was created using `cvx.Variable()`.

### optimization
So now that we have our objective function and constraints, we can solve for the values of $\mathbf{x}$.
cvxpy has the constructor `Problem(objective, constraints)`, which returns a `Problem` object.

The `Problem` object has a function solve(), which returns the minimum of the solution.  In this case, this is the minimum variance of the portfolio.

It also updates the vector $\mathbf{x}$.

We can check out the values of $x_A$ and $x_B$ that gave the minimum portfolio variance by using `x.value`

In [23]:
import cvxpy as cvx

def get_optimal_weights(covariance_returns, index_weights, scale=2.0):
    """
    Find the optimal weights.

    Parameters
    ----------
    covariance_returns : 2 dimensional Ndarray
        The covariance of the returns
    index_weights : Pandas Series
        Index weights for all tickers at a period in time
    scale : int
        The penalty factor for weights the deviate from the index 
    Returns
    -------
    x : 1 dimensional Ndarray
        The solution for x
    """
    assert len(covariance_returns.shape) == 2
    assert len(index_weights.shape) == 1
    assert covariance_returns.shape[0] == covariance_returns.shape[1]  == index_weights.shape[0]

    #TODO: Implement function
    m = len(index_weights)
    
    x = cvx.Variable(m)
    
    portfolio_variance = cvx.quad_form(x, covariance_returns)
    
    distance_to_index = cvx.norm(x-index_weights)
    
    objective = cvx.Minimize(portfolio_variance + scale*distance_to_index)
    
    constraints = [x >= 0, sum(x) == 1]
    
    problem = cvx.Problem(objective, constraints)
    
    problem.solve()
    
    return x.value

project_tests.test_get_optimal_weights(get_optimal_weights)

ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

Tests Passed


## Optimized Portfolio
Using the `get_optimal_weights` function, let's generate the optimal ETF weights without rebalanceing. We can do this by feeding in the covariance of the entire history of data. We also need to feed in a set of index weights. We'll go with the average weights of the index over time.

In [24]:
raw_optimal_single_rebalance_etf_weights = get_optimal_weights(covariance_returns.values, index_weights.iloc[-1])
optimal_single_rebalance_etf_weights = pd.DataFrame(
    np.tile(raw_optimal_single_rebalance_etf_weights, (len(returns.index), 1)),
    returns.index,
    returns.columns)

With our ETF weights built, let's compare it to the index. Run the next cell to calculate the ETF returns and compare it to the index returns.

In [25]:
optim_etf_returns = generate_weighted_returns(returns, optimal_single_rebalance_etf_weights)
optim_etf_cumulative_returns = calculate_cumulative_returns(optim_etf_returns)
project_helper.plot_benchmark_returns(index_weighted_cumulative_returns, optim_etf_cumulative_returns, 'Optimized ETF vs Index')

optim_etf_tracking_error = tracking_error(np.sum(index_weighted_returns, 1), np.sum(optim_etf_returns, 1))
print('Optimized ETF Tracking Error: {}'.format(optim_etf_tracking_error))

Optimized ETF Tracking Error: 0.05795012630412267


## Rebalance Portfolio Over Time
The single optimized ETF portfolio used the same weights for the entire history. This might not be the optimal weights for the entire period. Let's rebalance the portfolio over the same period instead of using the same weights. Implement `rebalance_portfolio` to rebalance a portfolio.

Reblance the portfolio every n number of days, which is given as `shift_size`. When rebalancing, you should look back a certain number of days of data in the past, denoted as `chunk_size`. Using this data, compute the optoimal weights using `get_optimal_weights` and `get_covariance_returns`.

In [37]:
def rebalance_portfolio(returns, index_weights, shift_size, chunk_size):
    """
    Get weights for each rebalancing of the portfolio.

    Parameters
    ----------
    returns : DataFrame
        Returns for each ticker and date
    index_weights : DataFrame
        Index weight for each ticker and date
    shift_size : int
        The number of days between each rebalance
    chunk_size : int
        The number of days to look in the past for rebalancing

    Returns
    -------
    all_rebalance_weights : list of Ndarrays
        The ETF weights for each point they are rebalanced
    """
    assert returns.index.equals(index_weights.index)
    assert returns.columns.equals(index_weights.columns)
    assert shift_size > 0
    assert chunk_size >= 0
    
    #TODO: Implement function
    all_rebalance_weights = []
    
    for i in range(chunk_size, len(returns), shift_size):
        data = returns.iloc[i - chunk_size : i]
        cov_returns = get_covariance_returns(data)
        optimal_weights = get_optimal_weights(cov_returns, index_weights.iloc[i - 1])
        all_rebalance_weights.append(optimal_weights)
    
    return all_rebalance_weights

project_tests.test_rebalance_portfolio(rebalance_portfolio)

[[ 2.97086366e-04 -1.49593881e-04 -8.82401092e-05]
 [-1.49593881e-04  1.68909932e-04  3.42159759e-05]
 [-8.82401092e-05  3.42159759e-05  5.57551203e-05]]
[[ 9.52870419e-05  1.12038842e-04 -1.21623321e-04]
 [ 1.12038842e-04  1.38162975e-04 -1.41646974e-04]
 [-1.21623321e-04 -1.41646974e-04  1.78251534e-04]]
[[ 0.00021947  0.00014665 -0.00013851]
 [ 0.00014665  0.00015309 -0.00014335]
 [-0.00013851 -0.00014335  0.00016908]]
[[ 1.24075147e-04  5.29089796e-05 -3.15785560e-05]
 [ 5.29089796e-05  7.63574647e-05 -4.96048472e-05]
 [-3.15785560e-05 -4.96048472e-05  2.57039883e-04]]
Tests Passed


Run the following cell to rebalance the portfolio using `rebalance_portfolio`.

In [38]:
chunk_size = 250
shift_size = 5
all_rebalance_weights = rebalance_portfolio(returns, index_weights, shift_size, chunk_size)

[[ 4.97130575e-04 -1.24172500e-05  7.30794234e-05 ...  2.45480367e-05
   1.22731182e-04  1.94181846e-05]
 [-1.24172500e-05  2.19133647e-04  7.45003912e-06 ...  1.28703252e-05
   3.20681483e-05 -5.87829479e-06]
 [ 7.30794234e-05  7.45003912e-06  2.09188084e-04 ...  3.19815432e-05
   6.61102206e-05  3.25454411e-05]
 ...
 [ 2.45480367e-05  1.28703252e-05  3.19815432e-05 ...  5.15389752e-05
   2.10346413e-05  1.98359580e-05]
 [ 1.22731182e-04  3.20681483e-05  6.61102206e-05 ...  2.10346413e-05
   3.61902991e-04  2.23353416e-05]
 [ 1.94181846e-05 -5.87829479e-06  3.25454411e-05 ...  1.98359580e-05
   2.23353416e-05  7.10258630e-05]]
[[ 5.08305337e-04 -1.13902374e-05  7.14672675e-05 ...  2.37857963e-05
   1.21000081e-04  2.05428098e-05]
 [-1.13902374e-05  2.17542991e-04  7.24637506e-06 ...  1.37168709e-05
   3.36930510e-05 -5.86473141e-06]
 [ 7.14672675e-05  7.24637506e-06  2.08368029e-04 ...  3.06073143e-05
   6.76962709e-05  3.17814719e-05]
 ...
 [ 2.37857963e-05  1.37168709e-05  3.0607314

[[4.96434164e-04 1.69626735e-05 7.55929233e-05 ... 3.18821322e-05
  1.30217238e-04 2.77045153e-05]
 [1.69626735e-05 1.78781538e-04 2.15050966e-05 ... 1.54285468e-05
  3.80398892e-05 9.91039171e-06]
 [7.55929233e-05 2.15050966e-05 2.06198111e-04 ... 3.39019941e-05
  7.98119475e-05 3.72510255e-05]
 ...
 [3.18821322e-05 1.54285468e-05 3.39019941e-05 ... 4.94105808e-05
  2.15714007e-05 2.41436772e-05]
 [1.30217238e-04 3.80398892e-05 7.98119475e-05 ... 2.15714007e-05
  4.15554947e-04 4.17174049e-05]
 [2.77045153e-05 9.91039171e-06 3.72510255e-05 ... 2.41436772e-05
  4.17174049e-05 8.18932697e-05]]
[[5.33828146e-04 1.89503166e-05 8.73689754e-05 ... 3.09574830e-05
  1.37923257e-04 3.31389284e-05]
 [1.89503166e-05 1.80477638e-04 2.51932426e-05 ... 1.63028451e-05
  3.98211398e-05 1.15843666e-05]
 [8.73689754e-05 2.51932426e-05 2.15646471e-04 ... 3.37664047e-05
  8.63777499e-05 4.28927393e-05]
 ...
 [3.09574830e-05 1.63028451e-05 3.37664047e-05 ... 4.81120089e-05
  2.08095081e-05 2.46484554e-05]

[[5.80447382e-04 4.53650767e-05 1.18038112e-04 ... 5.25162692e-05
  1.27120765e-04 3.46139230e-05]
 [4.53650767e-05 1.93690163e-04 5.30177829e-05 ... 3.16242096e-05
  6.06052955e-05 3.38318551e-05]
 [1.18038112e-04 5.30177829e-05 2.48933131e-04 ... 4.01713999e-05
  9.53241278e-05 5.37008626e-05]
 ...
 [5.25162692e-05 3.16242096e-05 4.01713999e-05 ... 7.87565749e-05
  2.87538522e-05 2.01040948e-05]
 [1.27120765e-04 6.06052955e-05 9.53241278e-05 ... 2.87538522e-05
  4.44462884e-04 6.60311495e-05]
 [3.46139230e-05 3.38318551e-05 5.37008626e-05 ... 2.01040948e-05
  6.60311495e-05 1.10765803e-04]]
[[5.91654196e-04 5.06285806e-05 1.11650185e-04 ... 5.40032084e-05
  1.18546273e-04 3.52877201e-05]
 [5.06285806e-05 1.96248528e-04 4.93966980e-05 ... 3.35816665e-05
  5.77040536e-05 3.28343034e-05]
 [1.11650185e-04 4.93966980e-05 2.48157944e-04 ... 3.78760164e-05
  9.00103337e-05 5.39753924e-05]
 ...
 [5.40032084e-05 3.35816665e-05 3.78760164e-05 ... 7.95858407e-05
  2.82019115e-05 1.87581329e-05]

[[6.13206101e-04 9.09080383e-05 1.18319136e-04 ... 7.82655604e-05
  6.69505397e-05 2.39173231e-05]
 [9.09080383e-05 1.77561222e-04 5.35102339e-05 ... 4.13400909e-05
  6.20617439e-05 3.54404213e-05]
 [1.18319136e-04 5.35102339e-05 2.70696366e-04 ... 4.03146565e-05
  1.04614084e-04 6.03583441e-05]
 ...
 [7.82655604e-05 4.13400909e-05 4.03146565e-05 ... 9.22913329e-05
  2.78813530e-05 2.02532163e-05]
 [6.69505397e-05 6.20617439e-05 1.04614084e-04 ... 2.78813530e-05
  4.17267331e-04 7.31133800e-05]
 [2.39173231e-05 3.54404213e-05 6.03583441e-05 ... 2.02532163e-05
  7.31133800e-05 1.23205838e-04]]
[[6.25658938e-04 1.02171043e-04 1.22842634e-04 ... 8.34188100e-05
  9.54429813e-05 2.71528817e-05]
 [1.02171043e-04 1.86365080e-04 5.70119873e-05 ... 4.41578861e-05
  7.07686620e-05 3.79814177e-05]
 [1.22842634e-04 5.70119873e-05 2.67180645e-04 ... 4.04377930e-05
  1.16656873e-04 5.95440330e-05]
 ...
 [8.34188100e-05 4.41578861e-05 4.04377930e-05 ... 9.36494903e-05
  4.09085031e-05 2.12489014e-05]

[[6.77555657e-04 9.86074126e-05 1.46881563e-04 ... 9.49093980e-05
  9.83219696e-05 2.24519352e-05]
 [9.86074126e-05 2.04438810e-04 6.08876556e-05 ... 4.85147379e-05
  8.07850607e-05 4.27905420e-05]
 [1.46881563e-04 6.08876556e-05 2.62648779e-04 ... 4.94863344e-05
  1.10152350e-04 6.22100196e-05]
 ...
 [9.49093980e-05 4.85147379e-05 4.94863344e-05 ... 1.05030914e-04
  5.75463258e-05 2.17184004e-05]
 [9.83219696e-05 8.07850607e-05 1.10152350e-04 ... 5.75463258e-05
  6.00578177e-04 6.73669765e-05]
 [2.24519352e-05 4.27905420e-05 6.22100196e-05 ... 2.17184004e-05
  6.73669765e-05 1.31187086e-04]]
[[6.71922488e-04 9.17119842e-05 1.42386264e-04 ... 9.61695051e-05
  9.10314819e-05 2.25619039e-05]
 [9.17119842e-05 2.20321686e-04 6.43775588e-05 ... 4.83970248e-05
  8.99413779e-05 4.83697535e-05]
 [1.42386264e-04 6.43775588e-05 2.62515752e-04 ... 5.02324675e-05
  1.10987779e-04 6.40305983e-05]
 ...
 [9.61695051e-05 4.83970248e-05 5.02324675e-05 ... 1.07146407e-04
  5.39213405e-05 2.38732002e-05]

[[5.84406465e-04 1.13875248e-04 1.19637284e-04 ... 1.01789514e-04
  7.49255361e-05 4.24088248e-05]
 [1.13875248e-04 2.82487081e-04 8.20344888e-05 ... 7.69639714e-05
  1.57541679e-04 9.91624469e-05]
 [1.19637284e-04 8.20344888e-05 4.00408642e-04 ... 5.68376720e-05
  2.06988658e-04 8.22763895e-05]
 ...
 [1.01789514e-04 7.69639714e-05 5.68376720e-05 ... 1.61278055e-04
  9.09148129e-05 5.32393290e-05]
 [7.49255361e-05 1.57541679e-04 2.06988658e-04 ... 9.09148129e-05
  1.07407035e-03 1.58905653e-04]
 [4.24088248e-05 9.91624469e-05 8.22763895e-05 ... 5.32393290e-05
  1.58905653e-04 1.96564093e-04]]
[[5.80083532e-04 1.10109421e-04 1.18220110e-04 ... 9.84880685e-05
  7.62503101e-05 4.17966842e-05]
 [1.10109421e-04 2.85277637e-04 8.17759705e-05 ... 7.97651908e-05
  1.59233031e-04 1.03596550e-04]
 [1.18220110e-04 8.17759705e-05 3.95598695e-04 ... 5.81678984e-05
  2.02555274e-04 8.19862120e-05]
 ...
 [9.84880685e-05 7.97651908e-05 5.81678984e-05 ... 1.69778816e-04
  9.06149380e-05 5.64513543e-05]

[[5.35911030e-04 1.26621456e-04 1.45373336e-04 ... 8.39493380e-05
  1.49237396e-04 7.56291040e-05]
 [1.26621456e-04 2.98513136e-04 1.08507627e-04 ... 7.18457313e-05
  1.79893721e-04 1.34041363e-04]
 [1.45373336e-04 1.08507627e-04 4.41323352e-04 ... 4.36331013e-05
  2.34910819e-04 9.76680192e-05]
 ...
 [8.39493380e-05 7.18457313e-05 4.36331013e-05 ... 1.83058035e-04
  9.04744805e-05 6.39212574e-05]
 [1.49237396e-04 1.79893721e-04 2.34910819e-04 ... 9.04744805e-05
  1.50396104e-03 2.03774016e-04]
 [7.56291040e-05 1.34041363e-04 9.76680192e-05 ... 6.39212574e-05
  2.03774016e-04 2.35522375e-04]]
[[5.36914982e-04 1.29136752e-04 1.45067314e-04 ... 8.45720468e-05
  1.53464766e-04 7.56661975e-05]
 [1.29136752e-04 3.05111112e-04 1.11030169e-04 ... 7.35645116e-05
  1.84348770e-04 1.36292137e-04]
 [1.45067314e-04 1.11030169e-04 4.32346095e-04 ... 4.64124432e-05
  2.36144966e-04 9.81466505e-05]
 ...
 [8.45720468e-05 7.35645116e-05 4.64124432e-05 ... 1.81890986e-04
  8.83418018e-05 6.34254518e-05]

[[4.63069589e-04 1.24281512e-04 1.30819750e-04 ... 5.61928741e-05
  1.65697393e-04 9.10904209e-05]
 [1.24281512e-04 3.14404528e-04 1.08708909e-04 ... 6.26813866e-05
  1.66357549e-04 1.24906796e-04]
 [1.30819750e-04 1.08708909e-04 4.49009372e-04 ... 4.15325221e-05
  2.33989607e-04 9.63615828e-05]
 ...
 [5.61928741e-05 6.26813866e-05 4.15325221e-05 ... 2.20118336e-04
  7.36380792e-05 6.66024189e-05]
 [1.65697393e-04 1.66357549e-04 2.33989607e-04 ... 7.36380792e-05
  1.46371395e-03 2.10281308e-04]
 [9.10904209e-05 1.24906796e-04 9.63615828e-05 ... 6.66024189e-05
  2.10281308e-04 2.34407137e-04]]
[[4.77083491e-04 1.28322053e-04 1.31363607e-04 ... 5.64673751e-05
  1.64372562e-04 9.17639674e-05]
 [1.28322053e-04 3.15119010e-04 1.08603977e-04 ... 6.26848525e-05
  1.66079489e-04 1.23873471e-04]
 [1.31363607e-04 1.08603977e-04 4.51388242e-04 ... 4.12906746e-05
  2.32767050e-04 9.51415950e-05]
 ...
 [5.64673751e-05 6.26848525e-05 4.12906746e-05 ... 2.19999150e-04
  7.33920653e-05 6.55945993e-05]

[[5.71976470e-04 1.20386721e-04 1.11429945e-04 ... 2.06556668e-05
  2.21157504e-04 7.70748676e-05]
 [1.20386721e-04 2.60134308e-04 7.66640601e-05 ... 3.64653098e-05
  1.27622769e-04 6.58850240e-05]
 [1.11429945e-04 7.66640601e-05 4.09174306e-04 ... 1.25134681e-05
  2.10483102e-04 6.06115314e-05]
 ...
 [2.06556668e-05 3.64653098e-05 1.25134681e-05 ... 1.91339532e-04
  3.51515464e-05 3.20185209e-05]
 [2.21157504e-04 1.27622769e-04 2.10483102e-04 ... 3.51515464e-05
  1.39408261e-03 1.69519909e-04]
 [7.70748676e-05 6.58850240e-05 6.06115314e-05 ... 3.20185209e-05
  1.69519909e-04 1.84562331e-04]]
[[5.65387460e-04 1.19528220e-04 1.04307940e-04 ... 1.97910691e-05
  2.12509187e-04 7.75259725e-05]
 [1.19528220e-04 2.58813398e-04 7.79574142e-05 ... 3.63080150e-05
  1.30490447e-04 6.54295122e-05]
 [1.04307940e-04 7.79574142e-05 4.01784879e-04 ... 1.31798607e-05
  1.98097622e-04 6.15237711e-05]
 ...
 [1.97910691e-05 3.63080150e-05 1.31798607e-05 ... 1.91881024e-04
  3.74744837e-05 3.18538262e-05]

[[5.36485465e-04 1.10066277e-04 9.69228160e-05 ... 2.00626237e-05
  2.12917703e-04 6.98535701e-05]
 [1.10066277e-04 2.19661362e-04 6.20643258e-05 ... 2.28976355e-05
  9.34693337e-05 4.94461253e-05]
 [9.69228160e-05 6.20643258e-05 2.97821616e-04 ... 1.69336236e-05
  1.13219751e-04 5.83435699e-05]
 ...
 [2.00626237e-05 2.28976355e-05 1.69336236e-05 ... 1.48361811e-04
  2.27735424e-05 2.90685749e-05]
 [2.12917703e-04 9.34693337e-05 1.13219751e-04 ... 2.27735424e-05
  9.59287524e-04 7.94541478e-05]
 [6.98535701e-05 4.94461253e-05 5.83435699e-05 ... 2.90685749e-05
  7.94541478e-05 1.46938498e-04]]
[[5.31404595e-04 1.09390393e-04 9.31005605e-05 ... 2.13597920e-05
  2.16223635e-04 6.90527256e-05]
 [1.09390393e-04 2.13582749e-04 6.12219953e-05 ... 2.57320018e-05
  9.08240183e-05 4.87305595e-05]
 [9.31005605e-05 6.12219953e-05 2.94413311e-04 ... 1.75579675e-05
  1.13496380e-04 5.78712380e-05]
 ...
 [2.13597920e-05 2.57320018e-05 1.75579675e-05 ... 1.46057897e-04
  2.36405570e-05 2.86887883e-05]

[[5.13844915e-04 7.46725575e-05 5.38280334e-05 ... 5.51032273e-06
  1.41426514e-04 4.71286493e-05]
 [7.46725575e-05 1.51785618e-04 2.17655662e-05 ... 1.43886580e-05
  4.80003699e-05 8.71123653e-06]
 [5.38280334e-05 2.17655662e-05 1.69866918e-04 ... 2.01575873e-05
  4.21806914e-05 2.89603636e-05]
 ...
 [5.51032273e-06 1.43886580e-05 2.01575873e-05 ... 1.26352683e-04
  1.22231501e-05 1.66626011e-05]
 [1.41426514e-04 4.80003699e-05 4.21806914e-05 ... 1.22231501e-05
  5.67671109e-04 4.59719595e-05]
 [4.71286493e-05 8.71123653e-06 2.89603636e-05 ... 1.66626011e-05
  4.59719595e-05 9.19975080e-05]]
[[5.15116955e-04 7.10547237e-05 5.22831134e-05 ... 6.17199409e-06
  1.42345981e-04 4.57123968e-05]
 [7.10547237e-05 1.47428234e-04 2.19922073e-05 ... 1.40648645e-05
  4.77670236e-05 8.83079159e-06]
 [5.22831134e-05 2.19922073e-05 1.68048318e-04 ... 1.86002676e-05
  4.39753961e-05 2.77791584e-05]
 ...
 [6.17199409e-06 1.40648645e-05 1.86002676e-05 ... 1.25740218e-04
  1.32204539e-05 1.53357997e-05]

## Portfolio Turnover
With the portfolio rebalanced, we need to use a metric to measure the cost of rebalancing the portfolio. Implement `get_portfolio_turnover` to calculate the annual portfolio turnover. We'll be using the formulas used in the classroom:

$ AnnualizedTurnover =\frac{SumTotalTurnover}{NumberOfRebalanceEvents} * NumberofRebalanceEventsPerYear $

$ SumTotalTurnover =\sum_{t,n}{\left | x_{t,n} - x_{t+1,n} \right |} $ Where $ x_{t,n} $ are the weights at time $ t $ for equity $ n $.

$ SumTotalTurnover $ is just a different way of writing $ \sum \left | x_{t_1,n} - x_{t_2,n} \right | $

In [57]:
def get_portfolio_turnover(all_rebalance_weights, shift_size, rebalance_count, n_trading_days_in_year=252):
    """
    Calculage portfolio turnover.

    Parameters
    ----------
    all_rebalance_weights : list of Ndarrays
        The ETF weights for each point they are rebalanced
    shift_size : int
        The number of days between each rebalance
    rebalance_count : int
        Number of times the portfolio was rebalanced
    n_trading_days_in_year: int
        Number of trading days in a year

    Returns
    -------
    portfolio_turnover  : float
        The portfolio turnover
    """
    assert shift_size > 0
    assert rebalance_count > 0
    
    #TODO: Implement function
    
    allsum = np.abs(np.diff(np.flip(all_rebalance_weights, axis=0), axis = 0))
    portfolio_turnover = (np.sum(allsum) / rebalance_count) * (n_trading_days_in_year//shift_size)
    
    return portfolio_turnover

project_tests.test_get_portfolio_turnover(get_portfolio_turnover)

Tests Passed


Run the following cell to get the portfolio turnover from  `get_portfolio turnover`.

In [58]:
print(get_portfolio_turnover(all_rebalance_weights, shift_size, len(all_rebalance_weights) - 1))

16.594080020340048


That's it! You've built a smart beta portfolio in part 1 and did portfolio optimization in part 2. You can now submit your project.

## Submission
Now that you're done with the project, it's time to submit it. Click the submit button in the bottom right. One of our reviewers will give you feedback on your project with a pass or not passed grade. You can continue to the next section while you wait for feedback.